-- Use a base de dados existente
USE treinamento_java_db;

-- Criar tabela ENDERECO se ainda não existir
CREATE TABLE IF NOT EXISTS ENDERECO (
        ID_ENDERECO BIGINT AUTO_INCREMENT PRIMARY KEY,
        RUA VARCHAR(255) NOT NULL,
        BAIRRO VARCHAR(100) NOT NULL,
        NUMERO VARCHAR(10),
        CIDADE VARCHAR(100) NOT NULL,
        UF VARCHAR(2) NOT NULL,
        CEP VARCHAR(10) NOT NULL
    );

-- Criar tabela USUARIO se ainda não existir
CREATE TABLE IF NOT EXISTS USUARIO (
        ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
        LOGIN VARCHAR(50) NOT NULL,
        SENHA VARCHAR(255) NOT NULL,
        NOME VARCHAR(250),
        CPF VARCHAR(14) NOT NULL,
        ENDERECO_ID BIGINT,
        FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID_ENDERECO)
    );