-- V1__Create_SISTEMA_and_USUARIO_PROCESSO_SISTEMA_tables.sql

-- Create SISTEMA table
CREATE TABLE SISTEMA (
    ID_SISTEMA BIGINT NOT NULL AUTO_INCREMENT,
    SIGLA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_SISTEMA)
);

-- Insert predefined data into SISTEMA table
INSERT INTO SISTEMA (SIGLA) VALUES ('PJE1G');
INSERT INTO SISTEMA (SIGLA) VALUES ('PJE2G');
INSERT INTO SISTEMA (SIGLA) VALUES ('PROJUDI');

-- Create USUARIO_PROCESSO_SISTEMA table
CREATE TABLE USUARIO_PROCESSO_SISTEMA (
    ID_USUARIO BIGINT NOT NULL,
    ID_SISTEMA BIGINT NOT NULL,
    NUMEROPROCESSO VARCHAR(25) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SISTEMA) REFERENCES SISTEMA(ID_SISTEMA)
);